# Use the official lightweight Python image.
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy local code to the container image.
COPY . .

# Install dependencies
RUN pip install --no-cache-dir pandas==1.3.4 scikit-learn==1.0.1 joblib==1.1.0

# Run the training script
CMD ["python", "train.py"]
